---
- name: Manage storage
  hosts: all
  become: true
  vars:
    storage_safe_mode: false
  tasks:
    - name: Create three LVM logical volumes under volume group 'vg1' spread over four disks
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: vg1
            type: lvm
            disks:
              - "/dev/sdb"
              - "/dev/sdc"
              - "/dev/sdd"
              - "/dev/sde"
            raid_level: "raid10"
            state: present
            volumes:
              - name: lv1
                size: "1g"
                mount_point: "/opt/test1"
              - name: lv2
                size: "1g"
                mount_point: "/opt/test2"
              - name: lv3
                size: "1g"
                mount_point: "/opt/test3"
        tags:
          - storage
